# -*- coding: utf-8 -*-
"""CKD_Stages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_VOQIwz5y4nHTisIWULhiO_H-yFRFZt

# GFR Bazlı Labelling
**ADIM 1**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer


warnings.filterwarnings('ignore')

# Metodolojik Şeffaflık: Tekrarlanabilirlik için Seed
SEED = 42
np.random.seed(SEED)

# Görsel Standartlar
plt.rcParams.update({'figure.dpi': 100, 'figure.facecolor': 'white', 'axes.grid': True})
RENK_PALETI = {1: '#2196F3', 2: '#4CAF50', 3: '#FF9800', 4: '#F44336', 5: '#9C27B0'}

"""# 1. Veri Hazırlama ve Ön İşleme"""

# ─────────────────────────────────────────────────────────────────────────────
#  --- 1. Veri Yükleme, Veri Seti Temini
# ─────────────────────────────────────────────────────────────────────────────
dosya_yolu = "/content/kidney_disease.csv"
df = pd.read_csv(dosya_yolu)
print(f"✅ Veri seti boyutu: {df.shape}\n")

print("🔎 İlk 5 satır:")
print(df.head(), "\n")

print("📊 Veri seti hakkında bilgi:")
print(df.info(), "\n")

##Standardizasyon İşlemleri(Veri Normalleştirme)

# --- 2.Genel ön işleme adımları
# id sütununu kaldırma
if 'id' in df.columns:
    df.drop('id', axis=1, inplace=True)
    print("🗑️ 'id' sütunu kaldırıldı.\n")

# classification sütunu (ckd -> 1, notckd -> 0)
print("🎯 Sütun 'classification' düzenleniyor...")
df['classification'] = df['classification'].astype(str).str.strip().replace({'ckd\t': 'ckd', 'notckd': 'notckd'})
df['classification'] = df['classification'].map({'ckd': 1, 'notckd': 0})
print("✅ 'classification' sütunu sayısal değerlere dönüştürüldü.\n")

# Kategorik ve sayısal sütunları ayırma
categorical_cols = df.select_dtypes(include='object').columns.tolist()
numerical_cols = df.select_dtypes(exclude='object').columns.tolist()
numerical_cols.remove('classification')  # hedefi sayısal sütunlardan çıkar

print(f"📊 Kategorik sütunlar ({len(categorical_cols)}): {categorical_cols}")
print(f"🔢 Sayısal sütunlar ({len(numerical_cols)}): {numerical_cols}\n")


# --- 3. Eksik Değer İşlemleri
# Eksik değer sayısı (ilk durum)
print("📉 Eksik değer sayıları (ilk durum):")
print(df.isnull().sum(), "\n")

##Eksik değerlerde;

# Kategorik değerleri en sık (mode) ile doldur
print("🔧 Kategorik eksik veriler dolduruluyor (mode)...")
cat_imputer = SimpleImputer(strategy='most_frequent')
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])
print("✅ Kategorik eksik veriler tamamlandı.\n")

# Sayısal değerleri ortalama ile doldur
print("🔧 Sayısal eksik veriler dolduruluyor (mean)...")
num_imputer = SimpleImputer(strategy='mean')
df[numerical_cols] = num_imputer.fit_transform(df[numerical_cols])
print("✅ Sayısal eksik veriler tamamlandı.\n")


# Eksik değerlerin istatistiksel yöntemlerle giderilmesi.
# Klinik Gerekçe: Yaş (age) için ortalama, Serum Kreatinin (sc) için
# aykırı değer hassasiyeti nedeniyle medyan doldurma uygulanmıştır.
# Klinik verilerde genellikle sağa çarpıktır (outlier çoktur),
# bu yüzden medyan (median) ile doldurmak istatistiksel olarak daha güvenlidir

df['age'] = df['age'].fillna(df['age'].mean())
df['sc'] = df['sc'].fillna(df['sc'].median())
print("\n✓ Eksik değerler klinik dağılım prensiplerine göre dolduruldu.")


# Eksik değer sayısı (son durum)
print("📉 Eksik değer sayıları (temizlendikten sonra):")
print(df.isnull().sum(), "\n")

"""# 2. Feature Engineering"""

# --- 4. ADIM: KLİNİK METRİKLERİN HESAPLANMASI (eGFR) ---
# Vektörize hesaplama: Tüm satırlar için aynı anda hesaplanır
# Formül: 175 * (sc^-1.154) * (age^-0.203)
df['egfr'] = 175 * (df['sc']**-1.154) * (df['age']**-0.203)

print("✓ eGFR değerleri MDRD formülü ile hesaplandı.")


# --- 5. ADIM: KDIGO 2012 REHBERİNE GÖRE EVRE ETİKETLEME ---
# Fonksiyon tanımlayıp 'apply' kullanmak yerine np.select (vektörize if-elif) kullanıyoruz.
# Bu yöntem hem daha profesyoneldir hem de daha hızlıdır.

kosullar = [
    (df['egfr'] >= 90),                      # Evre 1
    (df['egfr'] >= 60) & (df['egfr'] < 90),  # Evre 2
    (df['egfr'] >= 30) & (df['egfr'] < 60),  # Evre 3
    (df['egfr'] >= 15) & (df['egfr'] < 30)   # Evre 4
]

secenekler = [1, 2, 3, 4]

# Koşullara uymayan her şey (yani < 15 olanlar) varsayılan olarak 5 (Evre 5) atanır.
df['stage'] = np.select(kosullar, secenekler, default=5)

print("✓ KDIGO 2012 evreleme işlemi tamamlandı.")

# --- SONUÇ KONTROLÜ ---
print("\n[YENİ VERİ YAPISI]")
print(df[['age', 'sc', 'egfr', 'stage']].head())

# --- 6. SAĞLIKLI BİREYLERİN DIŞLANMASI ---

# Başlangıçtaki satır sayısını not edelim
baslangic_sayisi = len(df)

# Sadece 'ckd' etiketine sahip olanları tutalım
# (Daha önce 'classification' sütunu sayısal değerlere dönüştürüldüğü için doğrudan sayısal değerle filtreleme yapıyoruz)
df = df[df['classification'] == 1].copy()

# İndeksi sıfırlayalım (Analizlerde kayma olmaması için önemli)
df = df.reset_index(drop=True)

cikarilan_sayisi = baslangic_sayisi - len(df)

print("-" * 50)
print(f"✓ FİLTRELEME TAMAMLANDI")
print(f"Dışlanan Sağlıklı Birey Sayısı: {cikarilan_sayisi}")
print(f"Analize Devam Eden Hasta Sayısı: {len(df)}")
print("-" * 50)

# Yeni Evre Dağılımını Kontrol Edelim
print("\n[HASTA GRUBU İÇİNDE NİHAİ EVRE DAĞILIMI]")
print(df['stage'].value_counts().sort_index())

"""# 3: EDA (Keşifsel Veri Analizi)"""

import missingno as msno


# Metodolojik Şeffaflık: Tekrarlanabilirlik için Seed
SEED = 42
np.random.seed(SEED)
# Görsel Standartlar
plt.rcParams['figure.figsize'] = [18, 12]
sns.set_style("whitegrid")
# Evreler için profesyonel renk paleti
palet = {'1': '#2196F3', '2': '#4CAF50', '3': '#FF9800', '4': '#F44336', '5': '#9C27B0'}

print("─" * 50)
print("ADIM 3: HASTA ODAKLI EDA ANALİZİ (n=" + str(len(df)) + ")")
print("─" * 50)

# --- 3.1 NİHAİ EVRE DAĞILIMI ---
plt.figure(figsize=(10, 6))
counts = df['stage'].value_counts().sort_index()
percentage = (counts / len(df) * 100).values

ax = sns.barplot(x=counts.index.astype(str), y=counts.values, palette=palet, edgecolor='black', linewidth=1.2)
plt.title('Hasta Grubu İçinde Evre Dağılımı (Sınıf Dengesizliği Kontrolü)', fontsize=14, fontweight='bold')
plt.ylabel('Hasta Sayısı')
plt.xlabel('KBH Evresi (KDIGO 2012)')

# Bar üzerine yüzdeleri ekleyelim
for i, p in enumerate(ax.patches):
    ax.annotate(f'%{percentage[i]:.1f}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 10), textcoords='offset points', fontweight='bold')
plt.show()

# --- 3.2 KRİTİK KLİNİK TRENDLER (BOXPLOTS) ---
# Evre ilerledikçe değişmesi beklenen temel biyobelirteçler
# hemo (Hemoglobin), sod (Sodyum), bu (Kan Üre), bp (Kan Basıncı)
klinik_markerlar = ['hemo', 'sod', 'bu', 'bp']

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Evreler Arası Klinik Parametre Değişimi (Hasta Popülasyonu)', fontsize=16, fontweight='bold')

for i, marker in enumerate(klinik_markerlar):
    row, col = i // 2, i % 2
    # Aykırı değerleri temizlemeden görmek ama grafiği bozmamak için showfliers=False
    sns.boxplot(x='stage', y=marker, data=df, ax=axes[row, col], palette=palet, showfliers=False)
    sns.stripplot(x='stage', y=marker, data=df, ax=axes[row, col], color='black', size=2, alpha=0.3)
    axes[row, col].set_title(f'{marker.upper()} vs KBH Evresi', fontweight='bold')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# --- 3.3 KATEGORİK RİSK FAKTÖRLERİ (STACKED BAR) ---
# Diyabet (dm) ve Hipertansiyon (htn) evreler ilerledikçe artıyor mu?
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Hipertansiyon Dağılımı
htn_dist = pd.crosstab(df['stage'], df['htn'], normalize='index') * 100
htn_dist.plot(kind='bar', stacked=True, ax=ax1, color=['#A5D6A7', '#EF9A9A'], edgecolor='white')
ax1.set_title('Evre Bazında Hipertansiyon Prevalansı', fontweight='bold')
ax1.set_ylabel('Oran (%)')

# Diyabet Dağılımı
dm_dist = pd.crosstab(df['stage'], df['dm'], normalize='index') * 100
dm_dist.plot(kind='bar', stacked=True, ax=ax2, color=['#81D4FA', '#FFAB91'], edgecolor='white')
ax2.set_title('Evre Bazında Diyabet Prevalansı', fontweight='bold')
ax2.set_ylabel('Oran (%)')

# --- 3.4 EKSİK VERİ MATRİSİ (Metodolojik Doğrulama) ---
plt.figure(figsize=(10, 4))
msno.matrix(df, sparkline=False, color=(0.1, 0.38, 0.57))
plt.title('Eksik Veri Dağılım Matrisi', fontsize=14, fontweight='bold')
plt.show()

# --- 3.5 KORELASYON ANALİZİ VE SIZINTI KONTROLÜ ---
# Sadece sayısal sütunları seçelim
numerical_df = df.select_dtypes(include=['float64', 'int64'])
corr_matrix = numerical_df.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='RdBu_r', center=0)
plt.title('Klinik Değişkenler Arası Korelasyon Matrisi (Multicollinearity Check)', fontsize=14, fontweight='bold')
plt.show()

# --- 3.6 DEĞİŞKEN DAĞILIMLARI (Normallik Kontrolü) ---
# İmpütasyon stratejisini (mean vs median) haklı çıkarmak için
dist_markers = ['hemo', 'bu', 'sod']
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
for i, marker in enumerate(dist_markers):
    sns.histplot(df[marker], kde=True, ax=axes[i], color='#2196F3')
    axes[i].set_title(f'{marker.upper()} Dağılım Analizi', fontweight='bold')
plt.tight_layout()
plt.show()

"""# 4: Model Eğitimi"""

from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
import numpy as np

# 1. Ayarlamalar
# K=5 genellikle bu boyuttaki veri setleri için idealdir.
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=SEED)

# Performans sonuçlarını saklamak için listeler
f1_scores = []
reports = []

print("─" * 60)
print(f"ADIM 4: {skf.n_splits}-KATLI STRATIFIED CROSS VALIDATION BAŞLADI")
print("─" * 60)

# 2. Cross-Validation Döngüsü
# Not: Bilgi sızıntısını önlemek için Scaling işlemini döngü içinde yapıyoruz.
fold_no = 1
for train_index, test_index in skf.split(X, y):
    # Veriyi böl
    X_train_cv, X_test_cv = X.iloc[train_index], X.iloc[test_index]
    y_train_cv, y_test_cv = y.iloc[train_index], y.iloc[test_index]

    # Her katlama (fold) için ayrı ölçeklendirme (Data Leakage Koruması)
    cv_scaler = StandardScaler()
    X_train_cv_scaled = cv_scaler.fit_transform(X_train_cv)
    X_test_cv_scaled = cv_scaler.transform(X_test_cv)

    # Modeli Eğit
    model.fit(X_train_cv_scaled, y_train_cv)

    # Tahmin ve Değerlendirme
    y_pred = model.predict(X_test_cv_scaled)
    score = f1_score(y_test_cv, y_pred, average='weighted')
    f1_scores.append(score)

    print(f"Fold {fold_no} Tamamlandı - Weighted F1 Score: %{score*100:.2f}")
    fold_no += 1

# 3. Nihai Akademik Rapor
print("\n" + "="*60)
print("ÇAPRAZ DOĞRULAMA (CV) SONUÇ ÖZETİ")
print("="*60)
print(f"Ortalama F1-Score: %{np.mean(f1_scores)*100:.2f}")
print(f"Standart Sapma (Varyans): {np.std(f1_scores):.4f}")

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

# 2. Pipeline Oluşturma (Scaling + Model)
# Pipeline kullanmak, çapraz doğrulama sırasında bilgi sızıntısını (leakage)
# engellemenin en profesyonel yoludur.
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('rf', RandomForestClassifier(class_weight='balanced', random_state=42))
])

# Denenecek Parametre Havuzu (Grid)
param_grid = {
    'rf__n_estimators': [100, 200, 300],
    'rf__max_depth': [None, 10, 20],
    'rf__min_samples_split': [2, 5, 10],
    'rf__max_features': ['sqrt', 'log2']
}

# 3. GridSearchCV Kurulumu
# cv=5 (5-katlı çapraz doğrulama), scoring='f1_weighted'
grid_search = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1,
    verbose=1
)

print("─" * 60)
print("HİPERPARAMETRE OPTİMİZASYONU BAŞLADI")
print("─" * 60)

# Eğitimi Başlat (X ve y, sc/egfr içermeyen temiz verilerdir)
grid_search.fit(X, y)

# 4. En İyi Sonuçları Raporla
print("\n" + "="*60)
print(f"EN İYİ PARAMETRELER: {grid_search.best_params_}")
print(f"OPTIMİZE EDİLMİŞ F1-SCORE: %{grid_search.best_score_*100:.2f}")
print("="*60)

# En iyi modeli seçelim
best_honest_model = grid_search.best_estimator_

"""# SHAP Analizi"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, classification_report, confusion_matrix
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

print("─" * 60)
print("ADIM: Sınıf Dengesizliği Yönetimi, Model Eğitimi ve Detaylı Metrikler")
print("─" * 60)

# 1. Eğitim ve Test Seti Bölme
X_train_smote, X_test_smote, y_train_smote, y_test_smote = train_test_split(X, y, test_size=0.2, stratify=y, random_state=SEED)

# 2. Ölçeklendirme ve Imputasyon
scaler_smote = StandardScaler()
X_train_scaled_smote = scaler_smote.fit_transform(X_train_smote)
X_test_scaled_smote = scaler_smote.transform(X_test_smote)

imputer_smote = SimpleImputer(strategy='mean')
X_train_scaled_smote = imputer_smote.fit_transform(X_train_scaled_smote)
X_test_scaled_smote = imputer_smote.transform(X_test_scaled_smote)

# 3. SMOTE
smote = SMOTE(random_state=SEED)
X_resampled, y_resampled = smote.fit_resample(X_train_scaled_smote, y_train_smote)

# 4. XGBoost Model Eğitimi (Sınıflar 0-indexed olmalı: 1-5 -> 0-4)
xgb_model_smote = XGBClassifier(
    objective='multi:softprob',
    num_class=len(np.unique(y_resampled)),
    random_state=SEED,
    eval_metric='mlogloss',
    use_label_encoder=False
)
xgb_model_smote.fit(X_resampled, y_resampled - 1)

# 5. Tahminler (Tekrar 1-5 aralığına çekiliyor)
y_pred_smote = xgb_model_smote.predict(X_test_scaled_smote) + 1

# 6. PERFORMANS RAPORLAMASI (İstenen Metrikler)
print("\n" + "="*60)
print(f"SMOTE + XGBoost Model Weighted F1-Score: %{f1_score(y_test_smote, y_pred_smote, average='weighted')*100:.2f}")
print("="*60 + "\n")

print("SINIFLANDIRMA RAPORU (Precision, Recall, F1):")
print(classification_report(y_test_smote, y_pred_smote, target_names=['Evre 1', 'Evre 2', 'Evre 3', 'Evre 4', 'Evre 5']))

# 7. CONFUSION MATRIX
cm = confusion_matrix(y_test_smote, y_pred_smote)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Evre 1', 'Evre 2', 'Evre 3', 'Evre 4', 'Evre 5'],
            yticklabels=['Evre 1', 'Evre 2', 'Evre 3', 'Evre 4', 'Evre 5'])
plt.title('Confusion Matrix - SMOTE + XGBoost', fontsize=14, fontweight='bold')
plt.xlabel('Tahmin Edilen Evre')
plt.ylabel('Gerçek Evre')
plt.show()

from sklearn.model_selection import train_test_split
import shap
import matplotlib.pyplot as plt
import numpy as np

# Split X and y for SHAP analysis
X_train_shap, X_test_shap, y_train_shap, y_test_shap = train_test_split(X, y, test_size=0.2, stratify=y, random_state=SEED)

# 1. SHAP Explainer Oluşturma
model_for_shap = best_honest_model.named_steps['rf']
explainer = shap.TreeExplainer(model_for_shap)

# Test seti üzerinden SHAP değerlerini hesaplayalım
scaler_from_pipeline = best_honest_model.named_steps['scaler']
X_test_scaled_for_shap = scaler_from_pipeline.transform(X_test_shap)

# SHAP değerlerini hesapla
shap_values = explainer.shap_values(X_test_scaled_for_shap)

print("─" * 60)
print("ADIM 5: SHAP ANALİZİ VE KLİNİK YORUMLANABİLİRLİK")
print("─" * 60)

# 2. Global Özet Grafik (Bar Plot)
plt.figure(figsize=(12, 8))
plt.title("Özelliklerin Evre Tahmini Üzerindeki Genel Etkisi (Global SHAP)")
shap.summary_plot(shap_values, X_test_scaled_for_shap, feature_names=X.columns, plot_type="bar", show=False)
plt.show()

# 3. Spesifik Bir Evre İçin Beeswarm Grafiği (Evre 5 için)
# Not: shap_values bir liste ise hedef sınıfın indeksini alıyoruz.
target_class_idx = 4 # Evre 5 tahmini (0-indexed)

# Bazı SHAP versiyonlarında çıktı listesi yerine 3D array olabilir, kontrol ederek alıyoruz
if isinstance(shap_values, list):
    class_shap_values = shap_values[target_class_idx]
else:
    class_shap_values = shap_values[:, :, target_class_idx]

plt.figure(figsize=(12, 8))
plt.title(f"Evre {target_class_idx + 1} Tahmininde Değişkenlerin Rolü (Beeswarm Plot)")
shap.summary_plot(class_shap_values, X_test_scaled_for_shap, feature_names=X.columns, show=False)
plt.show()

"""Hyperparameter Optimization (Hiperparametre Optimizasyonu) ve Cross-Validation (Çapraz Doğrulama) kombinasyonudur."""

from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# 1. Veri Hazırlıđı (D&uuml;r&uuml;st Yaklaœım - Sızıntı Yok)
drop_cols = ['stage', 'egfr', 'sc', 'id', 'classification']
X_honest = df.drop(columns=[c for c in drop_cols if c in df.columns])
y_honest = df['stage']

# METİN DEđERLERİ SAYIYA &Ccedil;EVİRME (Hata Giderme)
# StandardScaler string deđerleri d&ouml;n&uuml;œt&uuml;remez, bu y&uuml;zden manuel mapping yapıyoruz
mapping = {
    'yes': 1, 'no': 0,
    'present': 1, 'notpresent': 0,
    'normal': 1, 'abnormal': 0,
    'good': 1, 'poor': 0
}

# Kategorik s&uuml;tunları bul ve d&ouml;n&uuml;œt&uuml;r
for col in X_honest.select_dtypes(include=['object']).columns:
    X_honest[col] = X_honest[col].astype(str).str.strip().str.lower().map(mapping)

# XGBoost sınıfların 0'dan baœlamasını bekler (1-5 -&gt; 0-4)
y_shifted = y_honest - 1

# 2. Eđitim/Test B&ouml;l&uuml;nmesi
X_train, X_test, y_train, y_test = train_test_split(
    X_honest, y_shifted, test_size=0.2, stratify=y_shifted, random_state=42
)

# 3. &Ouml;l&ccedil;eklendirme
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. XGBoost Model Eđitimi
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    objective='multi:softprob',
    random_state=42
)
xgb_model.fit(X_train_scaled, y_train)

# 5. Olasılık Tahminleri
y_probs = xgb_model.predict_proba(X_test_scaled)

# 6. Multiclass AUC-ROC Hesaplama
auc_roc = roc_auc_score(y_test, y_probs, multi_class='ovr', average='weighted')

print("─" * 60)
print(f"D&Uuml;R&Uuml;ST MODEL XGBOOST AUC-ROC SKORU: %{auc_roc*100:.2f}")